version: '2'

services:
  spark:
    container_name: spark
    image: omahoco/spark-postgres
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data
    ports:
      - '8100:8080'
networks:
  default:
    external:
      name: develop
